import 'dart:async';
import 'dart:io' show Platform;

import 'package:alchemist/alchemist.dart';
import 'package:wrap_my_finances/core/design_system/theme/app_theme.dart';

// Applies the app's real theme (AppColorsExtension/AppTypographyExtension/
// AppSpacingExtension) to every golden test in this project, so golden
// images actually exercise the design tokens rather than Alchemist's
// default Material theme. See US7/FR-014.
//
// Golden images must be generated on, and compared against, the same OS
// that renders them — even Alchemist's "ci" variant (Ahem font,
// obscured text) is not perfectly pixel-identical across platforms in
// practice, since Skia still rasterizes shapes/borders/shadows slightly
// differently between macOS and Linux. Developers here work on macOS; CI
// (.github/workflows/ci.yml) runs on `ubuntu-latest`. So each variant is
// enabled only in the environment it was generated for:
// - Locally (no `CI` env var): only the human-readable "platform" variant
//   runs, compared against goldens/macos/*.png, generated by developers.
// - In CI (GitHub Actions sets `CI=true`): only the "ci" variant runs,
//   compared against goldens/ci/*.png, generated from a Linux CI run (see
//   research.md).
final bool _isCi = Platform.environment.containsKey('CI');

Future<void> testExecutable(FutureOr<void> Function() testMain) async {
  return AlchemistConfig.runWithConfig(
    config: AlchemistConfig(
      theme: AppTheme.light,
      platformGoldensConfig: PlatformGoldensConfig(
        enabled: !_isCi,
        platforms: {HostPlatform.macOS},
      ),
      ciGoldensConfig: CiGoldensConfig(enabled: _isCi),
    ),
    run: testMain,
  );
}
